create table if not exists public.activity_logs (
  id bigint generated by default as identity primary key,
  event_type text not null,
  user_id text,
  user_tag text not null,
  content text not null,
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default timezone('utc', now())
);

create index if not exists activity_logs_created_at_idx
  on public.activity_logs (created_at desc);

create index if not exists activity_logs_user_id_idx
  on public.activity_logs (user_id);

create index if not exists activity_logs_event_type_idx
  on public.activity_logs (event_type);

create table if not exists public.voice_sessions (
  id bigint generated by default as identity primary key,
  user_id text not null,
  user_tag text not null,
  channel_id text not null,
  channel_name text not null,
  started_at timestamptz not null,
  ended_at timestamptz,
  duration_seconds integer,
  created_at timestamptz not null default timezone('utc', now())
);

create index if not exists voice_sessions_user_open_idx
  on public.voice_sessions (user_id, started_at desc)
  where ended_at is null;

create table if not exists public.system_status (
  service_name text primary key,
  status text not null,
  last_seen_at timestamptz not null,
  metadata jsonb not null default '{}'::jsonb
);

create table if not exists public.error_reports (
  id bigint generated by default as identity primary key,
  service text not null,
  source text not null,
  message text not null,
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default timezone('utc', now())
);

create index if not exists error_reports_service_created_idx
  on public.error_reports (service, created_at desc);
